services:
  postgres:
    image: postgres:16-alpine
    container_name: recipes-blog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipes_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./apps/api
    container_name: recipes-blog-api
    ports:
      - "4000:4000"
    env_file:
      - ./apps/api/.env
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/recipes_db?schema=public"
      PORT: 4000
      FRONTEND_URL: "https://recipes-blog-web.vercel.app"
      NEXT_PUBLIC_SITE_URL: "https://recipes-blog-web.vercel.app"
    depends_on:
      - postgres
    volumes:
      - ./apps/api/uploads:/app/uploads
      - ./apps/web/public/uploads:/app/src/../../web/public/uploads

volumes:
  postgres_data:
